---
abstract: 'SpookyHash implementation for Perl'
author:
  - 'Hideaki Ohno <hide.o.j55 {at} gmail.com>'
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build::Pluggable::CPANfile: 0.04
  Module::Build::Pluggable::GithubMeta: 0
  Module::Build::Pluggable::XSUtil: 1.01
configure_requires:
  ExtUtils::CBuilder: 0.28
  ExtUtils::ParseXS: 2.21
  Module::Build: 0.40
  Module::Build::Pluggable: 0
  Module::Build::Pluggable::CPANfile: 0.04
  Module::Build::Pluggable::GithubMeta: 0
  Module::Build::Pluggable::XSUtil: 1.01
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.130880'
keywords:
  - spooky
  - spookyhash
  - hash
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Digest-SpookyHash
no_index:
  directory:
    - t
    - xt
    - inc
    - eg
provides:
  Digest::SpookyHash:
    file: lib/Digest/SpookyHash.pm
    version: 0.04
requires:
  Exporter: 0
  XSLoader: 0.02
  perl: 5.008003
resources:
  bugtracker: https://github.com/hideo55/Digest-SpookyHash/issues
  homepage: https://github.com/hideo55/p5-Digest-SpookyHash/tree
  repository: git://github.com/hideo55/p5-Digest-SpookyHash.git
version: 0.04
x_test_requires:
  Test::More: 0.98
