---
abstract: 'SpookyHash implementation for Perl'
author:
  - 'Hideaki Ohno <hide.o.j55 {at} gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
  Module::Build::XSUtil: 0
dynamic_config: 0
generated_by: 'Minilla/v0.5.3, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Digest-SpookyHash
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Digest::SpookyHash:
    file: lib/Digest/SpookyHash.pm
    version: 1.03
requires:
  Exporter: 0
  XSLoader: 0
  perl: 5.008008
resources:
  bugtracker: https://github.com/hideo55/p5-Digest-SpookyHash/issues
  homepage: https://github.com/hideo55/p5-Digest-SpookyHash
  repository: git://github.com/hideo55/p5-Digest-SpookyHash.git
version: 1.03
x_contributors:
  - 'hideo55 <hide.o.j55@gmail.com>'
